[tool.poetry]
name = "copycoder"
version = "0.1.0"
description = "Add your description here"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "src/copycoder"}]

[tool.poetry.dependencies]
python = "^3.10"
opencv-python = "^4.10.0.84"
numpy = "^2.1.2"
pillow = "*"
scikit-learn = "*"
tqdm = "*"
python-dotenv = "^1.0.1"
anthropic = "^0.37.1"
scikit-image = "^0.24.0"
openai = "^1.52.2"
pytesseract = "^0.3.13"
gradio = "^5.4.0"
moviepy = "^1.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
